force-app/main/default/objects/Bi_Weekly_Reimbursement__c/Bi_Weekly_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Bi Weekly Reimbursement</label>
    <nameField>
        <label>Bi Weekly Reimbursement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bi Weekly Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Confirm_Hours__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirm Hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Count_Error_Check__c.field-meta.xml
<CustomField>
    <fullName>Count_Error_Check__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count Error Check</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Error_Hours__c.field-meta.xml
<CustomField>
    <fullName>Error_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error Hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ResetHourscheckController.cls
public with sharing class ResetHourscheckController {
    private ApexPages.StandardController stdController;
    public Boolean refreshPage {get; set;}
    
    public ResetHourscheckController(ApexPages.StandardController stdController) {
        this.stdController = stdController;
        this.refreshPage = false;
    }
    
    public PageReference resetFields() {
        Bi_Weekly_Reimbursement__c objBiReim = (Bi_Weekly_Reimbursement__c)stdController.getRecord();
        objBiReim.Confirm_Hours__c = false;
        objBiReim.Error_Hours__c = false;
        objBiReim.Count_Error_Check__c = 0;
        
        try {
            update objBiReim;
            refreshPage = true;
        } catch (DmlException e) {
            System.debug('Error =>'+e.getMessage());
        }
        
        return null;
    }
}