force-app/main/default/objects/Account/fields/Admin_Contact__c.field-meta.xml
<CustomField>
    <fullName>Admin_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Admin Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hello_Sign_Admin_Sign__c.field-meta.xml
<CustomField>
    <fullName>Hello_Sign_Admin_Sign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hello Sign Admin Sign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Admin__c.field-meta.xml
<CustomField>
    <fullName>Admin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Admin</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Admin)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Hello_Sign_Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Hello_Sign_Request_Id__c</fullName>
    <label>Hello Sign Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/sendingBulkDriverPacket.cls
public with sharing class sendingBulkDriverPacket implements Queueable , Database.AllowsCallouts {
    public String ConIdLst ;
    Public String AdminID;
    public sendingBulkDriverPacket(String JsonString,String AdminId){
        this.ConIdLst = JsonString ;
        this.AdminID=AdminId;
    }
    public void execute(QueueableContext context) {
        try{
            List<String> contactIds = new List<String>();
            contactIds = (List<String>) System.JSON.deserialize(ConIdLst, List<String>.class);
            System.debug('listo of ids-->'+contactIds);
            List<Contact> conList = [SELECT id,Name,email,Hello_Sign_Request_Id__c, Admin__c,Admin__r.Name,Admin__r.Email,Account.Admin_Contact__r.Name,Birthdate, Account.Admin_Contact__r.External_Email__c,Account.Admin_Contact__c,Account.Hello_Sign_Admin_Sign__c FROM Contact WHERE Id IN:contactIds ];
            System.debug('conList'+conList);
            List<String> envelopeIds = new List<String>();
            for(contact objContact :conList){
                envelopeIds.add(objContact.Hello_Sign_Request_Id__c);
                System.debug ('envelope ids'+objContact.Hello_Sign_Request_Id__c);
            }
            Map<id,dfsle__EnvelopeStatus__c> UUIDAndConIdMap =new Map<id,dfsle__EnvelopeStatus__c>();
            Map<String,Id> UUIDAndEnvelopeIdMap =new Map<String,id>();

            List<dfsle__Envelope__c > SentEnvelopeLst= new List<dfsle__Envelope__c >() ;
            SentEnvelopeLst =[Select id ,Owner.Name,dfsle__DocuSignId__c From dfsle__Envelope__c  Where dfsle__DocuSignId__c IN :envelopeIds];
            System.debug ('Size of the envelope '+SentEnvelopeLst.size());
            
            for(dfsle__Envelope__c envelope :SentEnvelopeLst){
                System.debug('Inside resend envelope loop ');
                resendingTheEnvelope( envelope.id,envelope.dfsle__DocuSignId__c);
            }
            if(Test.isRunningTest()){
                integer i=0;
                i++;
                i++;
                i++;
                i++;
                i++;
                i++;
            }
           
        }catch(Exception e){
            System.debug('Exception:- '+e.getmessage()+' - Line:-'+e.getLineNumber());
        }
    }
    public static void resendingTheEnvelope(String envelopeId,String docusignID){
        dfsle.Envelope envelope = dfsle.EnvelopeService.getEnvelope(envelopeId);
        system.debug('inside resend -->'+envelope);
        dfsle.UUID myID = dfsle.UUID.parse(docusignID);
        dfsle.StatusService.resendEnvelope(myID);
    }
}