force-app/main/default/objects/Account/fields/Bi_Weekly_Pay_Period__c.field-meta.xml
<CustomField>
    <fullName>Bi_Weekly_Pay_Period__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bi Weekly Pay Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pay_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>Pay_Period_Days__c</fullName>
    <label>Pay Period Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pay_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Pay_Period_Start_Date__c</fullName>
    <label>Pay Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/Bi_Weekly_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Bi Weekly Reimbursement</label>
    <nameField>
        <label>Bi Weekly Reimbursement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bi Weekly Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Confirm_Hours__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirm Hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bi Weekly Reimbursements</relationshipLabel>
    <relationshipName>Bi_Weekly_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Fuel_Price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Price__c</fullName>
    <label>Fuel Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/MPG__c.field-meta.xml
<CustomField>
    <fullName>MPG__c</fullName>
    <label>MPG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Biweek_Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Biweek_Reimbursement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Biweek Reimbursement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Admin)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Deactivated_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactivated_Date__c</fullName>
    <inlineHelpText>Date employee is deactivated. They will receive the fixed and last months variable.</inlineHelpText>
    <label>Deactivated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Driver_Type__c.field-meta.xml
<CustomField>
    <fullName>Driver_Type__c</fullName>
    <label>Driver Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver - Part Time</fullName>
            </value>
            <value>
                <fullName>Driver - Full Time</fullName>
            </value>
            <value>
                <fullName>Driver - Salary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Maintenance_and_Tires__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_and_Tires__c</fullName>
    <label>Maintenance and Tires</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ReimbursementStatement__c.field-meta.xml
<CustomField>
    <fullName>ReimbursementStatement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ReimbursementStatement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Driver/Manager</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Driver/Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SendEmail__c/fields/Send_email_from_code__c.field-meta.xml
<CustomField>
    <fullName>Send_email_from_code__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send email from code</description>
    <label>Send email from code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SendEmailonDeactivation__c/fields/Send_to_Driver__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Driver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to Driver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerConfig__c/fields/ContactTriggersendEmailForNewContact__c.field-meta.xml
<CustomField>
    <fullName>ContactTriggersendEmailForNewContact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Use in contact trigger helper class for sendEmailForNewContact method.</description>
    <label>ContactTriggersendEmailForNewContact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TrueDialog_Keys__c/TrueDialog_Keys__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TrueDialog Keys</label>
</CustomObject>

force-app/main/default/classes/WeeklyTimeSheetNotConfirmControllerTest.cls
@isTest
public with sharing class WeeklyTimeSheetNotConfirmControllerTest {
     public static testmethod void method1(){

        SendEmail__c customSetting2 =  new SendEmail__c();
        customSetting2.Name = 'Send Email For Compliance';
        customSetting2.Send_email_from_code__c= true;
        insert customSetting2;
        
        TrueDialog_Keys__c tdKeys = TestDataFactory.createTrueDialog(true);

        SendEmailonDeactivation__c objSendEmail = new SendEmailonDeactivation__c();
        objSendEmail.Name ='YearToDateReimbursementStatement'; //YearToDateReimbursementStatement
        objSendEmail.BCCEmailaddresses__c = 'tezt@gmail.com,test.email.com';
        objSendEmail.Send_to_Driver__c = true;
        insert objSendEmail;
        
        TriggerConfig__c customEmailSetting =  new TriggerConfig__c();
        customEmailSetting.Name = 'Defaulttrigger';
        customEmailSetting.ContactTriggersendEmailForNewContact__c = true;
        insert customEmailSetting;

        Vehicle_URL_Mapping__c veh = TestDataFactory.createVehicleData(true, 0);

        Account acc = new Account();     
        Contact con1 = new Contact();    
        UserRole userRole_1 = [SELECT Id FROM UserRole WHERE DeveloperName = 'EMD' LIMIT 1];
        Profile profile_1 = [SELECT Id FROM Profile WHERE Name = 'Customer Community Login User' LIMIT 1];
        User admin = [SELECT Id, Username, UserRoleId FROM User WHERE Profile.Name = 'System Administrator' AND UserRoleId = :userRole_1.Id LIMIT 1];
        User user_1;
        System.runAs(admin) {
            Account account_1 = TestDataFactory.createAccount(false,'Ermi',true);
            account_1.Bi_Weekly_Pay_Period__c = true;
            account_1.Pay_Period_Days__c = 6;
            account_1.Pay_Period_Start_Date__c = system.today().adddays(-7);
            insert account_1;
            
            List<Contact> lstContact1=TestDataFactory.createDriverContact(false, account_1.Id, 'Driver', veh.Name, 'paras.dhanani',  1);
            con1= lstContact1[0];
            con1.FirstName = 'Priyanka';
            con1.LastName = 'Gajera';
            con1.AccountId = account_1.Id;
            con1.External_Email__c = 'minkesjhh.patel1478@gmail.com';
            con1.Deactivated_Date__c = Null;
            con1.Role__c = 'Driver';
            con1.Driver_Type__c = 'Driver - Part Time';
            con1.Insurance_Attachment_Id__c = Null;
            con1.ReimbursementStatement__c = true;
            con1.Biweek_Reimbursement__c = True;
            con1.MailingState = 'MA';
            insert con1;
            
            user_1 = new User( 
                Email = 'yourusername@gmail.com',
                ProfileId = profile_1.Id, 
                UserName = 'yourusername@gmail.com', 
                Alias = 'Test',
                TimeZoneSidKey = 'America/New_York',
                EmailEncodingKey = 'ISO-8859-1',
                LocaleSidKey = 'en_US', 
                LanguageLocaleKey = 'en_US',
                ContactId = con1.Id,
                PortalRole = 'Manager',
                FirstName = 'Firstname',
                LastName = 'Lastname'
            );
            insert user_1;
        }
        
        Bi_Weekly_Reimbursement__c br = new Bi_Weekly_Reimbursement__c();
            br.Name = '03/06/2022 to 03/12/2022' ; 
            br.Contact__c = con1.Id;
            br.Start_Date__c = date.parse('03/06/2022');
            br.End_Date__c = system.today().adddays(-2);
            br.Confirm_Hours__c = False;
            br.MPG__c = con1.MPG__c;
            br.Maintenance_and_Tires__c = con1.Maintenance_and_Tires__c;
            br.Fixed_Amount__c = con1.Fixed_Amount__c;
            br.Status__c = 'Pending';
            br.Fuel_Price__c = 0;
        Insert br;
        
        WeeklyTimeSheetNotConfirmController objbatch = new WeeklyTimeSheetNotConfirmController();
        objbatch.getWeeklyDriversData();
    }
}