force-app/main/default/objects/Account/fields/Pay_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Pay_Period_Start_Date__c</fullName>
    <label>Pay Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vehicle_Types__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Types__c</fullName>
    <label>Vehicle Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2020 Ford F-150</fullName>
            </value>
            <value>
                <fullName>2020 Ford Escape</fullName>
            </value>
            <value>
                <fullName>2020 AWD Ford Escape</fullName>
            </value>
            <value>
                <fullName>2020 Ford F-250</fullName>
            </value>
            <value>
                <fullName>2020 Chevrolet Malibu</fullName>
            </value>
            <value>
                <fullName>2020 Dodge Journey</fullName>
            </value>
            <value>
                <fullName>2020 Dodge Durango</fullName>
            </value>
            <value>
                <fullName>2020 Ford Fusion</fullName>
            </value>
            <value>
                <fullName>2020 Full Size Sedan 2</fullName>
            </value>
            <value>
                <fullName>2020 Ford Taurus</fullName>
            </value>
            <value>
                <fullName>2020 Dodge Ram 2500</fullName>
            </value>
            <value>
                <fullName>2020 SUV 1</fullName>
            </value>
            <value>
                <fullName>2020 Mid Size Sedan 4</fullName>
            </value>
            <value>
                <fullName>2020 Full Size Sedan 3</fullName>
            </value>
            <value>
                <fullName>2020 Chevrolet Impala</fullName>
            </value>
            <value>
                <fullName>2020 Ford Explorer</fullName>
            </value>
            <value>
                <fullName>2021 Dodge Charger</fullName>
            </value>
            <value>
                <fullName>2021 Dodge Durango</fullName>
            </value>
            <value>
                <fullName>2020 Full-Size Sedan</fullName>
            </value>
            <value>
                <fullName>2020 Toyota Camry</fullName>
            </value>
            <value>
                <fullName>2020 Honda Civic</fullName>
            </value>
            <value>
                <fullName>2021 Ford F-250</fullName>
            </value>
            <value>
                <fullName>2021 Ford Escape</fullName>
            </value>
            <value>
                <fullName>2021 4x4 V8 Pickup Truck</fullName>
            </value>
            <value>
                <fullName>2021 Full Size SUV</fullName>
            </value>
            <value>
                <fullName>2021 Compact Sedan</fullName>
            </value>
            <value>
                <fullName>2021 Ford Fusion</fullName>
            </value>
            <value>
                <fullName>2021 Midsize Sedan</fullName>
            </value>
            <value>
                <fullName>2021 AWD Ford Escape</fullName>
            </value>
            <value>
                <fullName>2021 Dodge Journey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/Bi_Weekly_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Bi Weekly Reimbursement</label>
    <nameField>
        <label>Bi Weekly Reimbursement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bi Weekly Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Confirm_Hours__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirm Hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Count_Error_Check__c.field-meta.xml
<CustomField>
    <fullName>Count_Error_Check__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count Error Check</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Employee_Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Employee_Reimbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Bi Weekly Reimbursements</relationshipLabel>
    <relationshipName>Bi_Weekly_Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Error_Hours__c.field-meta.xml
<CustomField>
    <fullName>Error_Hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error Hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Fuel_Price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Price__c</fullName>
    <label>Fuel Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/IRS_Mileage_Rate__c.field-meta.xml
<CustomField>
    <fullName>IRS_Mileage_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRS Mileage Rate</label>
    <referenceTo>IRS_Mileage_Rate__c</referenceTo>
    <relationshipLabel>Bi Weekly Reimbursements</relationshipLabel>
    <relationshipName>Bi_Weekly_Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Vehicle_Value__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Value__c</fullName>
    <label>Vehicle Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Bi_Weekly_Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Bi_Weekly_Reimbursement__c</fullName>
    <label>Bi Weekly Reimbursement</label>
    <referenceTo>Bi_Weekly_Reimbursement__c</referenceTo>
    <relationshipLabel>Employees Mileage</relationshipLabel>
    <relationshipName>Employees_Mileage</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Fuel_Price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Price__c</fullName>
    <label>Fuel Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/IRS_Mileage_Rate__c.field-meta.xml
<CustomField>
    <fullName>IRS_Mileage_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IRS Mileage Rate</description>
    <label>IRS Mileage Rate</label>
    <referenceTo>IRS_Mileage_Rate__c</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gas_Prices__c/Gas_Prices__c.object-meta.xml
<CustomObject>
    <label>Gas Prices</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Gas Prices #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gas Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gas_Prices__c/fields/Fuel_Price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Price__c</fullName>
    <label>Fuel Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Gas_Prices__c/fields/Month_Year__c.field-meta.xml
<CustomField>
    <fullName>Month_Year__c</fullName>
    <label>Month Year</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TrueDialog_Keys__c/TrueDialog_Keys__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TrueDialog Keys</label>
</CustomObject>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/vehicle__c.field-meta.xml
<CustomField>
    <fullName>vehicle__c</fullName>
    <label>vehicle</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle_Value__c/Vehicle_Value__c.object-meta.xml
<CustomObject>
    <label>Vehicle Value</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Vehicle Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Value__c/fields/Vehicle_URL_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_URL_Mapping__c</fullName>
    <label>Vehicle URL Mapping</label>
    <referenceTo>Vehicle_URL_Mapping__c</referenceTo>
    <relationshipLabel>Vehicle Values</relationshipLabel>
    <relationshipName>Vehicle_Values</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ResetHourscheckControllerTest.cls
@isTest
public class ResetHourscheckControllerTest {
    
    @TestSetup
    static void makeData(){
        
        UserRole objUserRole = TestDataFactory.getUserRole();
        Profile objProfile = TestDataFactory.getUserProfile();
        User objAdmin = TestDataFactory.getSystemAdminUser(objUserRole.Id);
        User objGenUser;
        
        TriggerConfig__c triggerCustomSetting = TestDataFactory.triggerConfigCustomSetting(true);
        SendEmail__c sendEmailCustomSetting = TestDataFactory.sendEmailCustomSetting(true, 'Send Email For Compliance');
        TrueDialog_Keys__c tdKeys = TestDataFactory.createTrueDialog(true);
        IRS_Mileage_Rate__c irsRateObj = TestDataFactory.createIRSRate(true,0);
        List<Address__c> objAddress = TestDataFactory.createAddress(true, 10,12345);
        
        Vehicle_URL_Mapping__c objVehicleUrlMap = TestDataFactory.createVehicleData(false, 0);
        objVehicleUrlMap.Name = String.valueof(System.today().year())+ ' Full-Size Sedan';
        objVehicleUrlMap.vehicle__c = 'Full-Size Sedan';
        Insert objVehicleUrlMap;
        System.debug('vehicle url--@'+objVehicleUrlMap);
        
        Vehicle_URL_Mapping__c objVehicleUrlMap1 = [select Id,Name, Year__c, Vehicle__c, URL__c,Vehicle_Mapping__c from Vehicle_URL_Mapping__c];
        System.debug('vehicle url1--@'+objVehicleUrlMap1);
        
        Gas_Prices__c gasprice = new Gas_Prices__c();
        gasprice.City__c = 'Atlanta';
        gasprice.Fuel_Price__c = 3;
        gasprice.Month_Year__c = Date.today().addmonths(-1).tostartofmonth();
        gasprice.State__c = 'AK';
        insert gasprice;

        Account objAccount2;
        List<Vehicle_Value__c> lstVehicleValue;
        
        System.runAs(objAdmin) {
           
            objAccount2 = TestDataFactory.createAccount(true,'Test',true);
            objAccount2.Pay_Period_Start_Date__c = System.today().addDays(-100);
            objAccount2.Vehicle_Types__c = String.valueof(System.today().year())+ ' Full-Size Sedan';
            update objAccount2;
            
            lstVehicleValue = TestDataFactory.createVehicleValue(true, objAccount2.Id, objVehicleUrlMap1.Id);
            
            List<Contact> lstContact =TestDataFactory.createDriverContact(true, objAccount2.Id, 'Driver', objVehicleUrlMap.Name, 'testContact1', 1);
            List<Employee_Reimbursement__c> lstEmpReim =TestDataFactory.createPendingReimbursement(true,lstContact, 1, irsRateObj.Id);
            List<Bi_Weekly_Reimbursement__c> lstBiWeeklyReim =TestDataFactory.createBiweeklyReim(true, lstContact, System.TODAY(), System.TODAY().addDays(7), 1, irsRateObj.Id);
            List<Employee_Mileage__c> lstEmpMil = TestDataFactory.getEmpMileage(true, 1, lstEmpReim, lstBiWeeklyReim);
        }

    }
 
    @isTest
    static void testResetFields() {
        // Retrieve the test data created in @testSetup
        Bi_Weekly_Reimbursement__c objBiWeeklyReim = [SELECT Id, Confirm_Hours__c, Error_Hours__c, Count_Error_Check__c FROM Bi_Weekly_Reimbursement__c LIMIT 1];
        
        Test.startTest();
        
        // Create the standard controller and custom controller
        ApexPages.StandardController stdController = new ApexPages.StandardController(objBiWeeklyReim);
        ResetHourscheckController controller = new ResetHourscheckController(stdController);
        
        // Call the resetFields method
        controller.resetFields();
        
        Test.stopTest();
        // Retrieve the updated record
        objBiWeeklyReim = [SELECT Id, Confirm_Hours__c, Error_Hours__c, Count_Error_Check__c FROM Bi_Weekly_Reimbursement__c WHERE Id = :objBiWeeklyReim.Id];
        
        // Assert that the fields were reset
        System.assertEquals(false, objBiWeeklyReim.Confirm_Hours__c, 'Confirm_Hours__c should be false');
        System.assertEquals(false, objBiWeeklyReim.Error_Hours__c, 'Error_Hours__c should be false');
        System.assertEquals(0, objBiWeeklyReim.Count_Error_Check__c, 'Count_Error_Check__c should be 0');
        
        // Assert that the refreshPage property is set to true
        System.assertEquals(true, controller.refreshPage, 'refreshPage should be true');
    }
}