force-app/main/default/objects/Account/fields/True_Dialog__c.field-meta.xml
<CustomField>
    <fullName>True_Dialog__c</fullName>
    <defaultValue>false</defaultValue>
    <label>True Dialog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vehicle_Types__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Types__c</fullName>
    <label>Vehicle Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2020 Ford F-150</fullName>
            </value>
            <value>
                <fullName>2020 Ford Escape</fullName>
            </value>
            <value>
                <fullName>2020 AWD Ford Escape</fullName>
            </value>
            <value>
                <fullName>2020 Ford F-250</fullName>
            </value>
            <value>
                <fullName>2020 Chevrolet Malibu</fullName>
            </value>
            <value>
                <fullName>2020 Dodge Journey</fullName>
            </value>
            <value>
                <fullName>2020 Dodge Durango</fullName>
            </value>
            <value>
                <fullName>2020 Ford Fusion</fullName>
            </value>
            <value>
                <fullName>2020 Full Size Sedan 2</fullName>
            </value>
            <value>
                <fullName>2020 Ford Taurus</fullName>
            </value>
            <value>
                <fullName>2020 Dodge Ram 2500</fullName>
            </value>
            <value>
                <fullName>2020 SUV 1</fullName>
            </value>
            <value>
                <fullName>2020 Mid Size Sedan 4</fullName>
            </value>
            <value>
                <fullName>2020 Full Size Sedan 3</fullName>
            </value>
            <value>
                <fullName>2020 Chevrolet Impala</fullName>
            </value>
            <value>
                <fullName>2020 Ford Explorer</fullName>
            </value>
            <value>
                <fullName>2021 Dodge Charger</fullName>
            </value>
            <value>
                <fullName>2021 Dodge Durango</fullName>
            </value>
            <value>
                <fullName>2020 Full-Size Sedan</fullName>
            </value>
            <value>
                <fullName>2020 Toyota Camry</fullName>
            </value>
            <value>
                <fullName>2020 Honda Civic</fullName>
            </value>
            <value>
                <fullName>2021 Ford F-250</fullName>
            </value>
            <value>
                <fullName>2021 Ford Escape</fullName>
            </value>
            <value>
                <fullName>2021 4x4 V8 Pickup Truck</fullName>
            </value>
            <value>
                <fullName>2021 Full Size SUV</fullName>
            </value>
            <value>
                <fullName>2021 Compact Sedan</fullName>
            </value>
            <value>
                <fullName>2021 Ford Fusion</fullName>
            </value>
            <value>
                <fullName>2021 Midsize Sedan</fullName>
            </value>
            <value>
                <fullName>2021 AWD Ford Escape</fullName>
            </value>
            <value>
                <fullName>2021 Dodge Journey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/Bi_Weekly_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Bi Weekly Reimbursement</label>
    <nameField>
        <label>Bi Weekly Reimbursement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bi Weekly Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/Employee_Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Employee_Reimbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Bi Weekly Reimbursements</relationshipLabel>
    <relationshipName>Bi_Weekly_Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bi_Weekly_Reimbursement__c/fields/IRS_Mileage_Rate__c.field-meta.xml
<CustomField>
    <fullName>IRS_Mileage_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRS Mileage Rate</label>
    <referenceTo>IRS_Mileage_Rate__c</referenceTo>
    <relationshipLabel>Bi Weekly Reimbursements</relationshipLabel>
    <relationshipName>Bi_Weekly_Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Vehicle_Value__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Value__c</fullName>
    <label>Vehicle Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Bi_Weekly_Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Bi_Weekly_Reimbursement__c</fullName>
    <label>Bi Weekly Reimbursement</label>
    <referenceTo>Bi_Weekly_Reimbursement__c</referenceTo>
    <relationshipLabel>Employees Mileage</relationshipLabel>
    <relationshipName>Employees_Mileage</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/IRS_Mileage_Rate__c.field-meta.xml
<CustomField>
    <fullName>IRS_Mileage_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IRS Mileage Rate</description>
    <label>IRS Mileage Rate</label>
    <referenceTo>IRS_Mileage_Rate__c</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrueDialog_Keys__c/TrueDialog_Keys__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TrueDialog Keys</label>
</CustomObject>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/vehicle__c.field-meta.xml
<CustomField>
    <fullName>vehicle__c</fullName>
    <label>vehicle</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle_Value__c/Vehicle_Value__c.object-meta.xml
<CustomObject>
    <label>Vehicle Value</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Vehicle Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Value__c/fields/Vehicle_URL_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_URL_Mapping__c</fullName>
    <label>Vehicle URL Mapping</label>
    <referenceTo>Vehicle_URL_Mapping__c</referenceTo>
    <relationshipLabel>Vehicle Values</relationshipLabel>
    <relationshipName>Vehicle_Values</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AnnualTaxliabilityReportTest.cls
@istest
public class AnnualTaxliabilityReportTest {

    @TestSetup
    static void setupTestData() {
        
        UserRole objUserRole = TestDataFactory.getUserRole();
        Profile objProfile = TestDataFactory.getUserProfile();
        User objAdmin = TestDataFactory.getSystemAdminUser(objUserRole.Id);
        User objGenUser;
        
        TriggerConfig__c triggerCustomSetting = TestDataFactory.triggerConfigCustomSetting(true);
        SendEmail__c sendEmailCustomSetting1 = TestDataFactory.sendEmailCustomSetting(true, 'Send Email For Compliance');
        SendEmail__c sendEmailCustomSetting2 = TestDataFactory.sendEmailCustomSetting(true, 'ChangeTripStatusinTripLogBatch');
        TrueDialog_Keys__c tdKeys = TestDataFactory.createTrueDialog(true);
        IRS_Mileage_Rate__c irsRateObj = TestDataFactory.createIRSRate(true,0);
        List<Address__c> objAddress = TestDataFactory.createAddress(true, 10,12345);
        
        Vehicle_URL_Mapping__c objVehicleUrlMap = TestDataFactory.createVehicleData(false, 0);
        objVehicleUrlMap.Name = String.valueof(System.today().year())+ ' Full-Size Sedan';
        objVehicleUrlMap.vehicle__c = 'Full-Size Sedan';
        Insert objVehicleUrlMap;
        
        Account objAccount1;
        List<Vehicle_Value__c> lstVehicleValue;
        List<Contact> lstContact1;
        List<Contact> lstContact2;
        List<Contact> lstContact3;

        Profile objUserProfile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Login User' LIMIT 1];
        
        System.runAs(objAdmin) {
            
            objAccount1 = TestDataFactory.createAccount(true,'Delta account',true);
            
            lstVehicleValue = TestDataFactory.createVehicleValue(true, objAccount1.Id, objVehicleUrlMap.Id);
            
            lstContact1 = TestDataFactory.createDriverContact(true, objAccount1.Id, 'Driver', objVehicleUrlMap.Name, 'paras.dhanani',  1);
            lstContact2 = TestDataFactory.createDriverContact(true, objAccount1.Id, 'Manager', objVehicleUrlMap.Name, 'paras.dhanani',  1);
            lstContact3 = TestDataFactory.createDriverContact(true, objAccount1.Id, 'Admin', objVehicleUrlMap.Name, 'paras.dhanani',  1);

            objGenUser = TestDataFactory.createUser(true, objProfile.Id, lstContact1[0].Id);

            List<Employee_Reimbursement__c> lstEmpReim =TestDataFactory.createPendingReimbursement(true,lstContact1, 20, irsRateObj.Id);
            List<Bi_Weekly_Reimbursement__c> lstBiWeeklyReim =TestDataFactory.createBiweeklyReim(true, lstContact1, date.valueof(system.today().adddays(-14)),date.valueof(system.today().addDays(-1)), 2, irsRateObj.Id);
            List<Employee_Mileage__c> lstEmpMil = TestDataFactory.getEmpMileage(true, 10, lstEmpReim, lstBiWeeklyReim);
            
        }
    }

    @isTest
    static void constructorTest(){

        List<Account> lstAccounts = [SELECT Id FROM Account WHERE Name = 'Delta account' LIMIT 1];

        Test.startTest();
        Test.setCurrentPage(Page.AnnualTaxliabilityReport);
        String accid = ApexPages.currentPage().getParameters().put('accid',lstAccounts[0].Id);
        // String currentYear = ApexPages.currentPage().getParameters().put('currentYear',String.valueOf(System.today().year()));
        String currentYear = ApexPages.currentPage().getParameters().put('Year',String.valueOf(System.today().year()));
        AnnualTaxliabilityReport objClass = new AnnualTaxliabilityReport();
        AnnualTaxliabilityReport.TaxLiabilityWrapper obj = new AnnualTaxliabilityReport.TaxLiabilityWrapper();
        Test.stopTest();

        System.assertEquals(1, lstAccounts.size(), 'One Account Must be Created.');

    }
    @isTest
    static void constructorTest2(){

        List<Account> lstAccounts = [SELECT Id FROM Account WHERE Name = 'Delta account' LIMIT 1];

        Test.startTest();
        Test.setCurrentPage(Page.AnnualTaxliabilityReport);
        String accid = ApexPages.currentPage().getParameters().put('accid',lstAccounts[0].Id);
        // String currentYear = ApexPages.currentPage().getParameters().put('currentYear',String.valueOf(System.today().year()));
        String currentYear = ApexPages.currentPage().getParameters().put('Year',String.valueOf(System.today().addyears(1).year()));
        AnnualTaxliabilityReport objClass = new AnnualTaxliabilityReport();
        AnnualTaxliabilityReport.TaxLiabilityWrapper obj = new AnnualTaxliabilityReport.TaxLiabilityWrapper();
        Test.stopTest();

        System.assertEquals(1, lstAccounts.size(), 'One Account Must be Created.');

    }

    // @istest
    // public static void CreateData() {
    //     TriggerConfig__c triggerCustomSetting = TestDataFactory.triggerConfigCustomSetting(true);
    //     SendEmail__c sendEmailCustomSetting1 = TestDataFactory.sendEmailCustomSetting(true,'Send Email For Compliance');
    //     TrueDialog_Keys__c tdKeys = TestDataFactory.createTrueDialog(true);
    //     Vehicle_URL_Mapping__c vehicleObj = TestDataFactory.createVehicleData(true,0);
    //     IRS_Mileage_Rate__c irsRateObj = TestDataFactory.createIRSRate(true,0);

    //     UserRole userRole_1 = [SELECT Id FROM UserRole WHERE DeveloperName = 'EMD' LIMIT 1];
    //     Profile profile_1 = [SELECT Id FROM Profile WHERE Name = 'Customer Community Login User' LIMIT 1];
    //     User admin = [SELECT Id, Username, UserRoleId FROM User WHERE Profile.Name = 'System Administrator' AND UserRoleId = :userRole_1.Id LIMIT 1];
    //     Account acc = new Account();     
    //     List<Contact> conList = new List<Contact>();
    //     List<Employee_Reimbursement__c>reim =new List<Employee_Reimbursement__c>();
    //     List<Employee_Mileage__c> emp =new List<Employee_Mileage__c>();
    //     List<Bi_Weekly_Reimbursement__c> biweek= new List<Bi_Weekly_Reimbursement__c>();        
        
    //     System.runAs(admin) {
    //         acc = TestDataFactory.createAccount(false,'Test',true);
    //         acc.Vehicle_Types__c=vehicleObj.name;
    //         acc.True_Dialog__c = true;
    //         acc.Vehicle_Types__c = vehicleObj.Name;
    //         Insert acc;
    //         conList = TestDataFactory.createDriverContact(True, acc.Id, 'Driver', vehicleObj.Name, 'test.email', 1);       
            
    //         reim = TestDataFactory.createPendingReimbursement(false,conList,12,irsRateObj.id);
    //         reim[0].Status__c = 'Approved';
    //         reim[0].Month__c = date.today().addMonths(-1).Month() + '-' + date.today().addMonths(-1).Year();
    //         reim[0].Approved_Date__c = system.today();
    //         insert reim;
    //         biweek =TestDataFactory.createBiweeklyReim(True,conList,system.today().addDays(-15),system.today(),1,irsRateObj.id);            
           
    //         emp=TestDataFactory.getEmpMileage(true,3,reim,biweek);
            
    //         Test.startTest();
    //         Test.setCurrentPage(Page.AnnualTaxliabilityReport);
    //         String accid = ApexPages.currentPage().getParameters().put('accid',acc.Id);
    //         String currentYear = ApexPages.currentPage().getParameters().put('currentYear',String.valueOf(System.today().year()));
    //         AnnualTaxliabilityReport objClass = new AnnualTaxliabilityReport();
    //         AnnualTaxliabilityReport.TaxLiabilityWrapper obj = new AnnualTaxliabilityReport.TaxLiabilityWrapper();
    //         Test.stopTest();
    //     }
    // }
}