force-app/main/default/objects/Employee_Mileage__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/EmployeeReimbursement__c.field-meta.xml
<CustomField>
    <fullName>EmployeeReimbursement__c</fullName>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Employees Mileage</relationshipLabel>
    <relationshipName>Employees_Mileage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Rejected__c.field-meta.xml
<CustomField>
    <fullName>Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Reject trip record</inlineHelpText>
    <label>Rejected?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Date__c.field-meta.xml
<CustomField>
    <fullName>Trip_Date__c</fullName>
    <description>Date and Time Trip was Logged</description>
    <inlineHelpText>Date and Time Trip was Logged</inlineHelpText>
    <label>Trip Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Status__c.field-meta.xml
<CustomField>
    <fullName>Trip_Status__c</fullName>
    <label>Trip Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Approved Yet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Variable__c.field-meta.xml
<CustomField>
    <fullName>Variable__c</fullName>
    <formula>IF(ISPICKVAL(Activity__c,&quot;Business&quot;),Variable_Rate__c* Mileage__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Fuel_Price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Price__c</fullName>
    <label>Fuel Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/MissingFuelPrice.cls
public with sharing class MissingFuelPrice implements Database.Batchable<sObject> {

    public List<Employee_Mileage__c> start(Database.BatchableContext bc){
        String prevReim = System.now().addMonths(-1).format('MM-YYYY');
        List<Employee_Mileage__c> mils = [SELECT Id, Trip_Status__c, Variable__c, Trip_Date__c, Fuel_price__c, EmployeeReimbursement__r.Fuel_Price__c, EmployeeReimbursement__r.Name, EmployeeReimbursement__r.Contact_Id__r.Account.Name FROM Employee_Mileage__c WHERE EmployeeReimbursement__r.Month__c =: prevReim AND Rejected__c = False AND Approved_Date__c = null AND (Fuel_price__c = 0 OR Fuel_price__c = null) AND (NOT EmployeeReimbursement__r.Contact_Id__r.Account.Name IN ('GPS (General Production Service)','Flat Water Homes','Test Accounts','Acme Corporation','Sidney Electric')) AND (NOT EmployeeReimbursement__r.Contact_Id__r.Vehicle_Type__c LIKE '%Mileage Rate%')];
        return mils;
    }

    public void execute(Database.BatchableContext bc, List<Employee_Mileage__c> mils) {
        List<Employee_Mileage__c> updtMils = new List<Employee_Mileage__c>();
        for(Employee_Mileage__c mil : mils) {
            mil.Fuel_price__c = mil.EmployeeReimbursement__r.Fuel_Price__c;
            updtMils.add(mil);
        }

        if(updtMils.size() > 0){
            update updtMils;
        }
    }

    public void finish(Database.BatchableContext bc){}

}