force-app/main/default/objects/Contact/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Maintenance_and_Tires__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_and_Tires__c</fullName>
    <label>Maintenance and Tires</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Fuel_Price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Price__c</fullName>
    <label>Fuel Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Maintenance_and_Tires__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_and_Tires__c</fullName>
    <label>Maintenance and Tires</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gas_Prices__c/Gas_Prices__c.object-meta.xml
<CustomObject>
    <label>Gas Prices</label>
    <nameField>
        <displayFormat>GP-{0000}</displayFormat>
        <label>Gas Prices #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gas Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gas_Prices__c/fields/Fuel_Price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Price__c</fullName>
    <label>Fuel Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Gas_Prices__c/fields/Month_Year__c.field-meta.xml
<CustomField>
    <fullName>Month_Year__c</fullName>
    <label>Month Year</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TriggerConfig__c/fields/ContactTriCommunityReimCreate__c.field-meta.xml
<CustomField>
    <fullName>ContactTriCommunityReimCreate__c</fullName>
    <defaultValue>true</defaultValue>
    <label>ContactTriCommunityReimCreate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerConfig__c/fields/ContactTriggersendEmailForNewContact__c.field-meta.xml
<CustomField>
    <fullName>ContactTriggersendEmailForNewContact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Use in contact trigger helper class for sendEmailForNewContact method.</description>
    <label>ContactTriggersendEmailForNewContact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/vehicle__c.field-meta.xml
<CustomField>
    <fullName>vehicle__c</fullName>
    <label>vehicle</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/UpdateEmpReimFuelPriceTest.cls
/*
***************************************************
Description : Test calss for UpdateEmpReimFuelPrice
***************************************************
*/
@isTest
public class UpdateEmpReimFuelPriceTest {
    public static testMethod Void updateFuelPriceTestMethod() {
        TriggerConfig__c customEmailSetting =  new TriggerConfig__c();
        customEmailSetting.Name = 'Defaulttrigger';
        customEmailSetting.ContactTriggersendEmailForNewContact__c = true;
        customEmailSetting.ContactTriCommunityReimCreate__c = true;
        insert customEmailSetting;
        
        Vehicle_URL_Mapping__c objVehicleUrlMap = TestDataFactory.createVehicleData(false, 0);
        objVehicleUrlMap.Name = String.valueof(System.today().year())+ ' Full-Size Sedan';
        objVehicleUrlMap.vehicle__c = 'Full-Size Sedan';
        Insert objVehicleUrlMap;
        Account account = new Account();
        account = TestDataFactory.createAccount(true,'Delta account',true);
           
        Contact contact = new Contact();
        List<Contact> lstContact1;
        lstContact1 = TestDataFactory.createDriverContact(false, account.Id, 'Driver', objVehicleUrlMap.Name, 'paras.dhanani',  1);
        contact=lstContact1[0];
        contact.lastname = 'Test Contact';
        contact.AccountId = account.Id;
        contact.External_Email__c = 'test@test.com';
        contact.Fixed_Amount__c = 0.0;
        contact.MailingState = 'CA';
        contact.MailingCity = 'Canyon';
        contact.Activation_Date__c = system.today();
        insert contact;
        
        Employee_Reimbursement__c er = new Employee_Reimbursement__c();
        er.Contact_Id__c = contact.Id;
        er.month__c = '02-2018';
        er.Name = contact.lastname+':'+er.month__c;
        er.Status__c = 'Pending';
        er.Fuel_Price__c = null;
        er.MPG__c = 10;
        er.Maintenance_and_Tires__c = 24;
        er.Fixed_Amount__c = 10.10;
        insert er;
        
        Gas_Prices__c gas = new Gas_Prices__c();
        gas.City__c = 'Canyon';
        gas.State__c = 'CA';
        gas.Fuel_Price__c = 3.33;
        gas.Month_Year__c = date.newInstance(2018,02,01);
        insert gas;
        
        Test.startTest();
        UpdateEmpReimFuelPrice.updateFuelPrice(er.month__c);
        Test.stopTest();
    }
}