force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Admin)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Monthly_Approved_Variable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Approved_Variable_Amount__c</fullName>
    <formula>Total_Approved__c * Total_Variable_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Approved Variable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Total_Monthly_Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_Reimbursement__c</fullName>
    <formula>Fixed_Amount__c + Total_Monthly_Approved_Variable__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Monthly Reimbursement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tripslogs</relationshipLabel>
    <relationshipName>Tripslogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Deactivation_Flow__c.field-meta.xml
<CustomField>
    <fullName>Deactivation_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Deactivation Flow</description>
    <inlineHelpText>Deactivation Flow</inlineHelpText>
    <label>Deactivation Flow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Employee_Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Employee_Reimbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee Reimbursement</description>
    <inlineHelpText>Employee Reimbursement</inlineHelpText>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Tripslogs</relationshipLabel>
    <relationshipName>Tripslogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint</description>
    <inlineHelpText>Endpoint</inlineHelpText>
    <label>Endpoint</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Response</description>
    <inlineHelpText>Response</inlineHelpText>
    <label>Response</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Response_Data__c.field-meta.xml
<CustomField>
    <fullName>Response_Data__c</fullName>
    <label>Response Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>200 is Success and others are Fail</description>
    <inlineHelpText>200 is Success and others are Fail</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UploadConcurQuickExpenseTriplog.cls
/**
 * @Author: GetonCRM Solutions LLP
 * @Description: This class for post call in triplog and send total mileages.This class is called by Concer button on reimbursement object.
 * @Modification logs
 * ========================================================================================================================
 * @Date: 05 June 2020 | Sanket Goswami
 * @description: 
 * AI-000435
 */
global without sharing class UploadConcurQuickExpenseTriplog {
    public static final String MLOGACCOUNT = System.Label.Triplog_New_URL + ',' + System.Label.Triplog_New_URL2;
    Webservice static String postTotalReimbursement(Id accid,String empReMonth,String contactEmail,String totalReimburement){
        String resStatus;
        List<Account> accountList = [SELECT id,Triplog_API__c  FROM Account WHERE Triplog_API__c != null AND Id =: accid WITH SECURITY_ENFORCED];
        Contact conLst;
        if(contactEmail!=null){
            conLst =[SELECT id from Contact WHERE email =:contactEmail WITH SECURITY_ENFORCED];
        }
        String apiToken = accountList[0].Triplog_API__c;
        String baseURL = !MLOGACCOUNT.Contains(apiToken) ? StaticValues.TRIPLOG_BASEURL : StaticValues.MLOG_BASEURL;
        baseURL = (baseURL + '/api/uploadConcurQuickExpense');
        String todayDate = String.valueof(system.today().year()+'-'+date.today().addmonths(-1).month()+'-'+system.today().day());
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('email', contactEmail);
        gen.writeStringField('date', todayDate);
        if(totalReimburement == null){
          gen.writeNumberField('amount', 0);
          }else{
          gen.writeNumberField('amount', decimal.valueof(totalReimburement));
          }
        
        gen.writeStringField('expenseTypeCode','01466');
        gen.writeEndObject();
        String jsonstringconvert = gen.getAsString();

        List<Tripslog__c> objTripsloglist = new List<Tripslog__c>();
        Tripslog__c obj = new Tripslog__c();
        obj.Body__c = jsonstringconvert;
        obj.Endpoint__c = baseURL;
        obj.Total_Trips__c = 0;
        obj.Total_Mileages__c = 0;
        obj.Response__c = 'UploadConcurQuickExpenseTriplog';
        obj.Contact__c=conLst.Id;
        try {
            if(!Test.isRunningTest()) {
                HttpResponse res = ApiCalloutUtility.executeCallout(apiToken,'POST',baseURL,'',jsonstringconvert);
                system.debug('res'+res);
                obj.Response_Data__c = res.getBody();
                obj.Status__c = res.getStatusCode() == 200 ? 'Success' : 'Fail';
                obj.Deactivation_Flow__c = res.getStatusCode() == 200 ? true : false;
                List<String> resData = obj.Response_Data__c.split(':');
                resStatus = resData[1].substringBetween('"', '"}');
            }
        } catch(System.CalloutException er) {
            resStatus = 'Fail to send Expense to triplog';
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'Data is not send successfully.');
        }
        objTripsloglist.add(obj);
        if(!objTripsloglist.isEmpty()) {
            insert objTripsloglist;
        }
        return resStatus;
    }

    Webservice static void postTotalReimbursementForAllUser(Id accid){
        String varReim = System.Label.VarReim_Concur;
        List<Account> accountList = [SELECT id,Triplog_API__c  FROM Account WHERE Triplog_API__c != null AND Id =: accid WITH SECURITY_ENFORCED];
        String apiToken = accountList[0].Triplog_API__c;
        String baseURL = !MLOGACCOUNT.Contains(apiToken) ? StaticValues.TRIPLOG_BASEURL : StaticValues.MLOG_BASEURL;
        baseURL = (baseURL + '/api/uploadConcurQuickExpense');
        
        String lastMonth = Utils.fetchMonths(1, 0)[0]; 
        List<Tripslog__c> objTripsloglist = new List<Tripslog__c>();
        String todayDate = String.valueof(system.today().year()+'-'+date.today().addmonths(-1).month()+'-'+system.today().day());
        for(Employee_Reimbursement__c objReimbursemnt : [SELECT Id,Month__c,Total_Monthly_Reimbursement__c,Monthly_Approved_Variable_Amount__c,Contact_Id__r.External_Email__c ,Contact_Id__c
                                                            FROM Employee_Reimbursement__c 
                                                            WHERE Month__c =: lastMonth 
                                                            AND Contact_Id__r.AccountId =: accid limit 9999
                                                        ]){
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('email', objReimbursemnt.Contact_Id__r.External_Email__c );
            gen.writeStringField('date', todayDate);
          //  gen.writeStringField('amount', String.valueOf(objReimbursemnt.Total_Monthly_Reimbursement__c));
            if(varReim.contains(accid)) {
                if(objReimbursemnt.Monthly_Approved_Variable_Amount__c == null){
                    gen.writeNumberField('amount', 0);
                }else{
                    gen.writeNumberField('amount', objReimbursemnt.Monthly_Approved_Variable_Amount__c);
                }
            }else {
                if(objReimbursemnt.Total_Monthly_Reimbursement__c == null){
                    gen.writeNumberField('amount', 0);
                }else{
                    gen.writeNumberField('amount', objReimbursemnt.Total_Monthly_Reimbursement__c);
                }
            }
            gen.writeStringField('expenseTypeCode','01466');
            gen.writeEndObject();
            String jsonstringconvert = gen.getAsString();
            System.debug('jsonstringconvert : ' + jsonstringconvert);
    
            Tripslog__c obj = new Tripslog__c();
            obj.Body__c = jsonstringconvert;
            obj.Endpoint__c = baseURL;
            obj.Total_Trips__c = 0;
            obj.Total_Mileages__c = 0;
            obj.Response__c = 'UploadConcurQuickExpenseTriplog';
            obj.Contact__c=objReimbursemnt.Contact_Id__c;
            try {
                if(!Test.isRunningTest()) {
                    HttpResponse res = ApiCalloutUtility.executeCallout(apiToken,'POST',baseURL,'',jsonstringconvert);
                    system.debug('res'+res);
                    obj.Response_Data__c = res.getBody();
                    obj.Status__c = res.getStatusCode() == 200 ? 'Success' : 'Fail';
                    obj.Deactivation_Flow__c = res.getStatusCode() == 200 ? true : false;
                }
            } catch(System.CalloutException er) {
                ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'Data is not send successfully.');
            }
            objTripsloglist.add(obj);
        }
        
        if(!objTripsloglist.isEmpty()) {
            insert objTripsloglist;
        }
    }
}