force-app/main/default/objects/Contact/fields/Deactivated_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactivated_Date__c</fullName>
    <inlineHelpText>Date employee is deactivated. They will receive the fixed and last months variable.</inlineHelpText>
    <label>Deactivated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Driver_Type__c.field-meta.xml
<CustomField>
    <fullName>Driver_Type__c</fullName>
    <label>Driver Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver - Part Time</fullName>
            </value>
            <value>
                <fullName>Driver - Full Time</fullName>
            </value>
            <value>
                <fullName>Driver - Salary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Driver/Manager</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Driver/Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Send_Email_For_Submitted_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Send_Email_For_Submitted_Mileage__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Send Email For Submitted Mileage</description>
    <inlineHelpText>Send Email For Submitted Mileage</inlineHelpText>
    <label>Send Email For Submitted Mileage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Total_Mileage__c</fullName>
    <label>Total Mileage</label>
    <summarizedField>Employee_Reimbursement__c.Total_Mileage__c</summarizedField>
    <summaryFilterItems>
        <field>Employee_Reimbursement__c.Year__c</field>
        <operation>equals</operation>
        <value>2024</value>
    </summaryFilterItems>
    <summaryForeignKey>Employee_Reimbursement__c.Contact_Id__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Total_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Total_Mileage__c</fullName>
    <label>Total Mileage</label>
    <summarizedField>Employee_Mileage__c.Mileage__c</summarizedField>
    <summaryFilterItems>
        <field>Employee_Mileage__c.Activity__c</field>
        <operation>equals</operation>
        <value>Business</value>
    </summaryFilterItems>
    <summaryForeignKey>Employee_Mileage__c.EmployeeReimbursement__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SendEmail__c/fields/Send_email_from_code__c.field-meta.xml
<CustomField>
    <fullName>Send_email_from_code__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send email from code</description>
    <label>Send email from code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SendEmailToMe__c/fields/Send_email_to_me__c.field-meta.xml
<CustomField>
    <fullName>Send_email_to_me__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send email to me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SendEmailForSubmittedMileage.cls
Public class SendEmailForSubmittedMileage implements Database.Batchable<sObject>, Database.Stateful
{
    List<EmailTemplate> emailTemplate; 
    public List<Contact> objContactList;
    public Map<Id, Employee_Reimbursement__c> contactToEmpReimMap;
    public OrgWideEmailAddress[] owea;

    public SendEmailForSubmittedMileage() {
        List<String> lstAccountNames = new List<String>();
        
        
        if(System.Label.BatchAccountName!=null)
        {
            if(System.Label.BatchAccountName.contains(','))
            {
                lstAccountNames= System.Label.BatchAccountName.split(',');
            }              
        }
        objContactList = new List<Contact>();
        Set<Id> conIds = new Set<Id>();
        contactToEmpReimMap = new Map<Id, Employee_Reimbursement__c>();
        emailTemplate = [SELECT Id, Body, Subject, HTMLValue FROM EmailTemplate WHERE DeveloperName = 'Notification_for_total_mileage'];
        String strOWEEmail= System.Label.Driver_Service_OWE;
        owea = [select Id ,Address from OrgWideEmailAddress where Address =:strOWEEmail];
        Date todayDate = System.today();
        if(!Test.isRunningTest()) {
            objContactList = [SELECT Id, Role__c, Deactivated_Date__c,
                                        External_Email__c, FirstName 
                                    FROM Contact 
                                    WHERE (Role__c ='Driver' 
                                            OR Role__c = 'Driver/Manager' 
                                            OR Role__c =: StaticValues.roleAdminDriver) 
                                        AND ( Deactivated_Date__c >:todayDate 
                                            OR Deactivated_Date__c =:Null) 
                                        AND (Account.name IN: lstAccountNames) 
                                        AND Send_Email_For_Submitted_Mileage__c=:true 
                                        AND (Driver_Type__c !='Driver - Full Time' 
                                        OR Driver_Type__c != 'Driver - Part Time') ];
        } else {
            objContactList = [SELECT Id, Role__c, Deactivated_Date__c,
                                        External_Email__c, FirstName 
                                    FROM Contact WHERE Role__c ='Driver'                                  
                                        /*AND (Account.name IN: lstAccountNames)*/ LIMIT 1];
        }
        for(Contact c : objContactList) {
            conIds.add(c.Id);
        }
        
        String lastMonth = Utils.fetchMonths(1, 0)[0];
        List<Employee_Reimbursement__c> empReimList;
        if(!Test.isRunningTest()) {
        empReimList = [SELECT Id, Name, Month__c, Contact_Id__c, Total_Mileage__c 
                                                            FROM Employee_Reimbursement__c 
                                                            WHERE Month__c =: lastMonth AND Contact_Id__c IN: conIds AND Total_Mileage__c > 0];
        } else {
            empReimList = [SELECT Id, Name, Month__c, Contact_Id__c, Total_Mileage__c 
                                                            FROM Employee_Reimbursement__c ];
        }
        system.debug('empReimList=='+empReimList);
        for(Employee_Reimbursement__c empReim : empReimList) {
            contactToEmpReimMap.put(empReim.Contact_Id__c, empReim);
        }
    }

    Public List<Contact> start(Database.BatchableContext bc) {
        return objContactList;
    }

    Public void execute(Database.BatchableContext bc, List<Contact> scope) {
        List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
        String htmlbody = '';
        String htmlSubject = '';
        Messaging.SingleEmailMessage mail;
        for(Contact c : scope) {
            if(contactToEmpReimMap.containsKey(c.id)) {
                String[] monthYear = contactToEmpReimMap.get(c.id).Month__c.split('-');
                String mon = monthYear[0];
                if(mon == '01'){ mon = 'January';}
                else if (mon == '02'){ mon = 'February';}
                else if (mon == '03'){ mon = 'March';}
                else if (mon == '04'){ mon = 'April';}
                else if (mon == '05'){ mon = 'May';}
                else if (mon == '06'){ mon = 'June';}
                else if (mon == '07'){ mon = 'July';}
                else if (mon == '08'){ mon = 'August';}
                else if (mon == '09'){ mon = 'September';}
                else if (mon == '10'){ mon = 'October';}
                else if (mon == '11'){ mon = 'November';}
                else if (mon == '12'){ mon = 'December';}
                // Send Mail Functionality
                mail = new Messaging.SingleEmailMessage();
                SendEmailToMe__c  objSendEmailToMe = SendEmailToMe__c.getValues('SendEmailForSubmittedMileage');
                List<String> address = new List<String>();
                if(objSendEmailToMe.Send_email_to_me__c == true)
                {
                    address.add('minkeshp@askemc.com');
                    mail.setBCCAddresses(new string[]{'driverservices@mburse.com'});                    
                }
                else
                {
                    address.add(c.External_Email__c);
                    mail.setBCCAddresses(new string[]{'driverservices@mburse.com'});
                }                
                
                mail.setToAddresses(address);
                mail.setSubject(mon + ' Submitted mileage');
                htmlbody = emailTemplate[0].HTMLValue;
                if(owea.size()>0) {
                    mail.setOrgWideEmailAddressId(owea.get(0).Id);
                }
                htmlbody = htmlbody.replace('{!Contact.FirstName}',c.FirstName);
                htmlbody = htmlbody.replace('{!$Label.Driver_Forword_Logo}', System.Label.Driver_Forword_Logo);
                htmlbody = htmlbody.replace('{!Month}', mon);
                htmlbody = htmlbody.replace('{!Year}', monthYear[1]);
                htmlbody = htmlbody.replace('{!Total_Mileage}', String.valueOf(contactToEmpReimMap.get(c.Id).Total_Mileage__c));
                mail.setPlainTextBody(htmlbody);
                mail.setHtmlBody(htmlbody);
                mailList.add(mail);
            }
        }
        SendEmail__c  objSendEmail = SendEmail__c.getValues('SendEmailForSubmittedMileage');
        if(!mailList.isEmpty()  &&(objSendEmail!=null) && (objSendEmail.Send_email_from_code__c==true) && !Test.isRunningTest())  {
            Messaging.sendEmail(mailList);   
        }
    }

    Public void finish(Database.BatchableContext bc) {
        System.debug('sendemailforsubmittedmileage batch is completed');
    }
}