force-app/main/default/objects/Contact/fields/Notification_Message__c.field-meta.xml
<CustomField>
    <fullName>Notification_Message__c</fullName>
    <label>Notification Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Total_Mileage__c</fullName>
    <label>Total Mileage</label>
    <summarizedField>Employee_Reimbursement__c.Total_Mileage__c</summarizedField>
    <summaryFilterItems>
        <field>Employee_Reimbursement__c.Year__c</field>
        <operation>equals</operation>
        <value>2024</value>
    </summaryFilterItems>
    <summaryForeignKey>Employee_Reimbursement__c.Contact_Id__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Total_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Total_Mileage__c</fullName>
    <label>Total Mileage</label>
    <summarizedField>Employee_Mileage__c.Mileage__c</summarizedField>
    <summaryFilterItems>
        <field>Employee_Mileage__c.Activity__c</field>
        <operation>equals</operation>
        <value>Business</value>
    </summaryFilterItems>
    <summaryForeignKey>Employee_Mileage__c.EmployeeReimbursement__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <displayFormat>M-{00000000}</displayFormat>
        <label>Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Contacts__c.field-meta.xml
<CustomField>
    <fullName>Contacts__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Contact_Conversations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Notification_Message__c.field-meta.xml
<CustomField>
    <fullName>Notification_Message__c</fullName>
    <label>Notification Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Unread__c.field-meta.xml
<CustomField>
    <fullName>Unread__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unread</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/updateTenthMsgBatch.cls
/**
 * @description       : 
 * @author            : Vatsal Bhalani
 * @group             : 
 * @last modified on  : 08-02-2024
 * @last modified by  : Vatsal Bhalani
**/


// @Date : 20/05/2024 || Vatsal Bhalani
// Need to Run manully => On the 4th of each month after the batch has been run.
public class updateTenthMsgBatch implements Database.Batchable<sObject> {
    private List<Id> accountIds;
    String monthValue;
    String query;
    // Default constructor - fetches all account IDs
    public updateTenthMsgBatch() {
        
         monthValue = getMonthValue();
        
            query ='SELECT id, Total_Mileage__c, Contact_Id__c  FROM Employee_Reimbursement__c  WHERE month__c = :monthValue';
    }

    // Parameterized constructor - takes a specific list of account IDs
    public updateTenthMsgBatch(List<String> listAccountName) {
             monthValue = getMonthValue();
            query ='SELECT id, Total_Mileage__c, Contact_Id__c  FROM Employee_Reimbursement__c  WHERE month__c = :monthValue AND Contact_Id__r.Account.Name IN:listAccountName';
        }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Employee_Reimbursement__c> lstEmpReim) {
        Map<Id, Decimal> totalMileagemap = new Map<Id, Decimal>();
        String lastMonthString = RecordUtilityClass.getMonthName(monthValue);

        for (Employee_Reimbursement__c objEmpReim : lstEmpReim) {
            totalMileagemap.put(objEmpReim.Contact_Id__c, objEmpReim.Total_Mileage__c);
        }

        List<Message__c> lstMsgToInsert = new List<Message__c>();
        for (Id objContactId : totalMileagemap.keySet()) {
            List<String> args = new String[]{'0', 'number', '###,###,##0.00'};
            String updatedTotalMileage = String.format(totalMileagemap.get(objContactId).format(), args);
            System.debug(updatedTotalMileage);

            Message__c objMsg = new Message__c(
                Unread__c = true,
                Notification_Message__c = 'Your ' + lastMonthString + ' Mileage Was ' + updatedTotalMileage + ' .',
                Contacts__c = objContactId
            );

            lstMsgToInsert.add(objMsg);
        }

        if (!lstMsgToInsert.isEmpty()) {
            try {
                Database.insert(lstMsgToInsert, false);
            } catch (Exception e) {
                System.debug('Insertion Error: ' + e.getMessage());
            }
        }
    }
    private static string getMonthValue(){
       
        date lastMonth = System.today().addmonths(-1);
        return lastMonth.month() > 9 
        ? string.valueOf(lastMonth.month()) + '-' + string.valueOf(lastMonth.Year()) 
        : '0' + string.valueOf(lastMonth.month()) + '-' + string.valueOf(lastMonth.Year());
    }
    public void finish(Database.BatchableContext bc) {
        return;
    }
}